### ISSUE TITLE
I want to install this theme on Arch Linux

### ISSUE THREAD

**Issue by PILIHU2022** [fufexan/dotfiles#10]
How can I install this theme on Arch Linux?

**Comment by fufexan** [comment]
What theme exactly?

**Comment by PILIHU2022** [comment]
[This](https://user-images.githubusercontent.com/36706276/236707086-ea6cb781-8b0c-45d3-b6a1-2c6a4d5e2582.png)

**Comment by PILIHU2022** [comment]
Arch Linux hyprland

**Comment by fufexan** [comment]
For the bar, you can take a look at [eww](https://github.com/fufexan/dotfiles/tree/main/home/programs/eww), instructions are there.
For the Hyprland config, you'd have to copy and adjust [this file](https://github.com/fufexan/dotfiles/blob/main/home/wayland/hyprland/config.nix). There are several Nix-specific things in there that must be replaced, such as workspace generation, program names, colors.

**Comment by PILIHU2022** [comment]
Ok,thank you very much!
