### ISSUE TITLE
Question: Issues with the homeConfigurations

### ISSUE THREAD

**Issue by Mikilio** [fufexan/dotfiles#13]
Basically when I wanted to try out your homeConfigurations. It was throwing some weird errors to me. First encounter would be that they don't show on `nix flake show`.
I did some digging and readjustments to make it work for me but I'm not any smarter. The issues seems to be related to some weird magic I found [here](https://github.com/fufexan/dotfiles/blob/6534ff07ef181f5ec4de6ec06b26e020eb1b9877/home/profiles/default.nix#L14-L15) and [here](https://github.com/fufexan/dotfiles/blob/6534ff07ef181f5ec4de6ec06b26e020eb1b9877/home/profiles/default.nix#L52C7-L58C22). I figured these must be related to [this](https://github.com/fufexan/dotfiles/blob/6534ff07ef181f5ec4de6ec06b26e020eb1b9877/modules/default.nix#L7C4-L12C5) and that you want to somehow bring the parameters usually carried over by flake-parts to be in scope or something but I'm only guessing.
Maybe a GitHub issue isn't the right way to ask but I would love to hear an explanation.

Another thing to mention would be that I tried this in a Non-NixOS system with home-manager installed. So it's not weird that it might break for me when it works for you. The whole point of this issue is just because I want to learn. And then maybe improve on it.

**Comment by fufexan** [comment]
`nix flake show` won't show errors (or the configs themselves) from `homeConfigurations` since that output attribute is not in the flake schema.
> I did some digging and readjustments to make it work for me but I'm not any smarter. The issues seems to be related to some weird magic I found [here](https://github.com/fufexan/dotfiles/blob/6534ff07ef181f5ec4de6ec06b26e020eb1b9877/home/profiles/default.nix#L14-L15) and [here](https://github.com/fufexan/dotfiles/blob/6534ff07ef181f5ec4de6ec06b26e020eb1b9877/home/profiles/default.nix#L52C7-L58C22).

Yeah, the first snippet actually brings `inputs'` and `self'` into the module system args so they can be used inside the configs themselves. The magic isn't in how I use them, the magic lies within flake-parts.

In any case, if you still get errors, can you post them here so I can get an idea of what's going wrong? If we resolve this I might add a check for `home-manager` so such breakages don't happen in the future.

**Comment by Mikilio** [comment]
As I said for me it wasn't about the errors but here is one when running.

```console
home-manager switch --flake .#server
warning: Using saved setting for 'extra-substituters = https://nix-community.cachix.org https://helix.cachix.org https://fufexan.cachix.org https://nix-gaming.cachix.org https://hyprland.cachix.org https://cache.privatevoid.net' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= helix.cachix.org-1:ejp9KQpR1FBI2onstMQ34yogDm4OgU2ru6lIwPvuCVs= fufexan.cachix.org-1:LwCDjCJNJQf5XD2BV+yamQIMZfcKWR9ISIFy5curUsY= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4= hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= cache.privatevoid.net:SErQ8bvNWANeAvtsOESUwVYr2VJynfuc9JRwlzTTkVg=' from ~/.local/share/nix/trusted-settings.json.
warning: ignoring untrusted substituter 'https://nix-community.cachix.org'
warning: ignoring untrusted substituter 'https://helix.cachix.org'
warning: ignoring untrusted substituter 'https://fufexan.cachix.org'
warning: ignoring untrusted substituter 'https://nix-gaming.cachix.org'
warning: ignoring untrusted substituter 'https://hyprland.cachix.org'
warning: ignoring untrusted substituter 'https://cache.privatevoid.net'

error: value is a set while a list was expected

       at /nix/store/f9b94pl246pd7rqwvq0wh9hhpxs7xxlg-source/home/profiles/default.nix:57:19:

           56|       server = homeManagerConfiguration {
           57|         modules = homeImports.server ++ module_args;
             |                   ^
           58|         inherit pkgs;
(use '--show-trace' to show detailed location information)

```

I think it might be better to use perSystems and add the flake outputs like [here](https://flake.parts/define-custom-flake-attribute.html)

I fix this one btw either by removing module_args or putting it in [] the fact that it makes no difference makes me question it's purpose

**Comment by Mikilio** [comment]
As you inspired my config I might as well show you how it looks on my setup.
 [Config](https://github.com/Mikilio/dotfiles/blob/main/home/profiles/default.nix)

**Comment by fufexan** [comment]
> I fix this one btw either by removing module_args or putting it in [] the fact that it makes no difference makes me question it's purpose

I think it makes no difference right now as we have `inputs'` and `self'`, but back when we didn't it made a huge difference.

> I think it might be better to use perSystems and add the flake outputs like [here](https://flake.parts/define-custom-flake-attribute.html)

I think that may work.

**Comment by Mikilio** [comment]
Ok, so to summarize:
Because homeConfigurations are undefined top-level attributes whatever modules we import are not processed by flake-parts. To counteract we add the inputs that usually flake-parts would provide ourselves, by adding them to _module.args.

So far correct?

**Comment by fufexan** [comment]
Yes, that's right.
