### ISSUE TITLE
xdg-desktop-portal  setup

### ISSUE THREAD

**Issue by leiserfg** [fufexan/dotfiles#14]
Are you using xdg-desktop-portal with home-manager standalone?, if so, do you have any pointers to make it work?

**Comment by fufexan** [comment]
No, it's taken care of by the Hyprland NixOS module. Simply `programs.hyprland.enable` in your NixOS config.
If you don't use NixOS, I don't know how to help.

**Comment by leiserfg** [comment]
That's a pity, I have to use home-manager standalone so I can't depend on nixos modules. Thanks for your time anyway.
