### ISSUE TITLE
error: attribute 'fufexan' missing trying to install eww-hyprland

### ISSUE THREAD

**Issue by 2Epik4u** [fufexan/dotfiles#16]
when trying to import ``inputs.fufexan.homeManagerModules.eww-hyprland`` it gives me error: attribute 'fufexan' missing. 
full log in the github gist and my config is here: https://github.com/2Epik4u/nixos-config

https://gist.github.com/2Epik4u/2cc8e2b9e74ea57db18d5525fa9aa27c

**Comment by fufexan** [comment]
You added my flake with the name `fufexan-dotfiles` ([source](https://github.com/2Epik4u/nixos-config/blob/main/flake.nix#L9)). So, use `inputs.fufexan-dotfiles.homeManagerModules.eww-hyprland`.
