### ISSUE TITLE
Eww not opening?

### ISSUE THREAD

**Issue by greed-d** [fufexan/dotfiles#20]
Distro : Arch 
WM : Hyprland

I'm pretty new to eww and followed the steps you told but it spawns errors when trying to open the bar 

```bash
2023-10-25T06:22:25.040Z INFO  eww > Initializing Eww server. (/run/user/1000/eww-server_aa08eec3e14d83d6)
Run `eww logs` to see any errors while editing your configuration.
 2023-10-25T06:22:25.040Z INFO  eww::server > Loading paths: config-dir: /home/greed/.config/eww, ipc-socket: /run/user/1000/eww-server_aa08eec3e14d83d6, log-file: /home/greed/.cache/eww_aa08eec3e14d83d6.log
error: No variable named `EWW_TIME` in scope
  ┌─ ./modules/clock.yuck:6:25
  │
6 │       :text {formattime(EWW_TIME, "%a %b %d  %H:%M")})))
  │                         ──────── Used here
  │
  → Hint: Either define it as a global variable, or add it to the argument-list of your `defwidget` and pass it as an argument
  → Hint: If you meant to use the literal value "EWW_TIME", surround the value in quotes

```

and doing `eww open bar` gives this error 

```bash
failed to open window `bar`

Caused by:
    No window named 'bar' exists in config.
    This may also be caused by your config failing to load properly, please check for any other errors in that case.
```

Sorry for the silly question :(

**Comment by fufexan** [comment]
What's your eww version? Looks like it's pretty old. The `$EWW_TIME` magic variable was added in May iirc.

**Comment by greed-d** [comment]
`eww --version` gives : 

`eww 0.4.0 d58d91de78d2b9984a1bbb8314be197bc0e283dc`

I installed eww today, if that helps

**Comment by fufexan** [comment]
Yeah that's more than a year old. You may want to use `eww-git` from the AUR.

**Comment by greed-d** [comment]
![20231026095020_1](https://github.com/fufexan/dotfiles/assets/58597122/019714a2-a670-466b-b100-34df4c18a7bd)

I compiled the eww myself and I think I got all the deps but I could be wrong but it is like this

**Comment by fufexan** [comment]
Did you link one of the `css/colors-{dark,light}.scss` to `css/colors.scss`? Looks like the css is incomplete. You can find more in `eww logs`.

**Comment by greed-d** [comment]
![20231026144444_1](https://github.com/fufexan/dotfiles/assets/58597122/2d576ea6-6dd3-484d-9024-572372099366)
Yessir but still not complete :(

**Comment by fufexan** [comment]
Not complete in what sense? I don't see anything missing.
Oh, blur? You need to add these in your Hyprland config:
```ini
$layers = ^(eww-.+|bar|system-menu)$
layerrule = blur, $layers
layerrule = ignorealpha 0, $layers
layerrule = ignorealpha 0.5, ^(eww-music)$
layerrule = ignorealpha 0.5, ^(eww-calendar|system-menu)$
layerrule = xray 1, ^(bar)$
```

**Comment by greed-d** [comment]
![image](https://github.com/fufexan/dotfiles/assets/58597122/5fe2cecb-7358-477a-af24-8fd7451140bd)

that what's my sys info looks like 

compared to this 

![fufexan sys info](https://github.com/fufexan/dotfiles/assets/58597122/7cef35bc-85d3-4c10-839b-7cf64f3b94d9)
 
yours is league better

and even the right of the bar looks like this 

![image](https://github.com/fufexan/dotfiles/assets/58597122/52b7af54-4401-48be-b272-baa2f2108025)

vs yours 

![fufexan bar right](https://github.com/fufexan/dotfiles/assets/58597122/05387f86-d67a-4bb8-876b-dc1e9af4f959)

Sorry for the annoyance I'm causing :sweat:

**Comment by fufexan** [comment]
Those are old versions, but I didn't have time to change the screenshots. You can get them from the commit I added those screenshots in. Easier found that way, as I don't version my config. For the bluetooth, I assume you don't have an adapter, so that's why it's not showing. If you do, there's an issue with the script.
