### ISSUE TITLE
Having trouble when setting hyprlock as login manager

### ISSUE THREAD

**Issue by hmanhng** [fufexan/dotfiles#36]
Don't recognize keyboard in `hyprlock` if `hyprlock` is set to `exec-one`

**Comment by fufexan** [comment]
Can you explain further? How is the keyboard not recognized? Typing but characters don't show up?

**Comment by hmanhng** [comment]
yes, I can't type anything
when i `ctrl+alt+F2` , login and run `Hyprland` then can enter

**Comment by hmanhng** [comment]
I've tried rebooting a few times, and sometimes it works, sometimes it doesn't

**Comment by fufexan** [comment]
Have you tried `systemctl restart greetd`? Might be a first-run issue with greetd.

**Comment by hmanhng** [comment]
> Have you tried `systemctl restart greetd`? Might be a first-run issue with greetd.

if I set `services.getty.autologinUser = "hmanhng";` and
```
programs.fish.loginShellInit = ''
  set TTY1 (tty)
  [ "$TTY1" = "/dev/tty1" ] && exec Hyprland
'';
```
that still happens

**Comment by fufexan** [comment]
Very weird. Never happened to me.

**Comment by hmanhng** [comment]
> Very weird. Never happened to me.

I revised the config and it worked.

 Also I have been having problems with hyprland for several months
 Sometimes when I start Hyprland and open any application, it turns on but the screen doesn't show anything.
 I know it's still open because I can `win + enter` open the terminal and `reboot` even though I don't see anything

**Comment by hmanhng** [comment]
NIt happened on both of my lenovo laptops.  1 runs Intel and 1 runs AMD.
 Once it starts again, it's completely normal.  sometimes it happens
 
And my new laptop running amd chip completely shut down after I lid closed the computer.  Is there any way to fix it bro?

**Comment by fufexan** [comment]
Might be a Hyprland bug. Open an issue there.

**Comment by hmanhng** [comment]
ty
