### ISSUE TITLE
How to use Lanzeboote from nixos-install

### ISSUE THREAD

**Issue by hmanhng** [fufexan/dotfiles#37]
I tried using Lanzeboote when reinstalling from the iso.  But when I reboot it doesn't find the nixos efi
 Looks like `sudo sbctl create-keys` is needed.  Is there a way I can install it from the iso without commenting the lanzeboote module and re-enable it after a successful installation?

**Comment by hmanhng** [comment]
Can you show me the steps you take when reinstalling the machine?

**Comment by fufexan** [comment]
I don't think I've reinstalled the machine since enabling lanzaboote, but running `sbctl` should be possible even in the live iso.

**Comment by hmanhng** [comment]
thk sir
