### ISSUE TITLE
 Amazing flake, can i ask something?

### ISSUE THREAD

**Issue by andresparrab** [fufexan/dotfiles#4]
Hello i just saw you screenshot and it look just amazin, simple yet so artistic.
I have just learn about hyprland one month ago and i have it on my arch installation.

But now i iwant to try an nixos installation, with hyperland and eww, i mena like yours.

if i understand correctly i just have to download all this repo and start in a usb and mount the drives and just 
nixos-install --flake .#<host>? and i will have exactly the same setup as yours?
thank you for any answer

**Comment by fufexan** [comment]
> if i understand correctly i just have to download all this repo and start in a usb and mount the drives and just
> nixos-install --flake .#? and i will have exactly the same setup as yours?

Not exactly. While you can install this configuration, you will have to tweak it for your hardware. For example you will need to partition your drive in the liveboot, then run `nixos-generate-config`, replace the `hardware-configuration.nix` in `hosts/io` (in this repo, assuming you will clone it). Then you also have to disable the agenix secrets, as you will not have my SSH keys to decrypt those. After that there may still be some options that you may have to tweak, but that's about it for installing.

I have a few useful links for you:
- https://nixos.org/manual/nixos/stable/
- https://nixos.wiki/wiki/Flakes

**Comment by andresparrab** [comment]
Hello!
i had copy my hardware.nix to host.io
and try to change everywhere where password was an so on, but still did not work.
i think i know to little about flakes and more.I try to read but is very difficult when i read and the see your config i still dont get it.
Is it possible to have a simple flake just with your hyperland config? like the eww abr theme i mean all the hyperland stuff and i by my self start installing packags my self and configure the system?
I use lmost all the stuff you use, but you have a very impressive and advnace config that is out of my knoglewde right now.

i have spend now like 2 days and not sleep trying to figure this out. and i asked hyperland community in discor and the answer was .
It cant be done, nixos and hyperland is impossible dotn do it!

but i totally see you ahve and amazing setting just how i want it, so it is possible

i have so far installed the system with xfce, and sddm and i writing from this now,but i totally into hyperland
i hope maybe you could help me. thank you so much in advance

**Comment by fufexan** [comment]
> Is it possible to have a simple flake just with your hyperland config? like the eww abr theme i mean all the hyperland stuff and i by my self start installing packags my self and configure the system?

Yes, you only have to include the `home/wayland/hyprland` directory along with the `home/programs/eww` directory in your configuration, and it should mostly work. You will also have to install the fonts I use for eww in your system config.

> I use lmost all the stuff you use, but you have a very impressive and advnace config that is out of my knoglewde right now.

I think the fact that I use `flake-parts` is the most confusing here. You can take a look in the repo's history to see how things evolved since the beginning of these dotfiles. I think the commit messages are at least somewhat explanatory.


> and i asked hyperland community in discor and the answer was .
> It cant be done, nixos and hyperland is impossible dotn do it!

There are many NixOS users who use Hyprland, so I'm not sure who could've come up with that.

Good luck with getting your config to work as you want it! Also you can message me on Discord as well if you need more direct help.

**Comment by andresparrab** [comment]
Thanks I will try follow your tips and start getting into it.
I have sussesfully make a simple flake with just flake.nic, configurations.nix and home.nix and hardware of course.
And I will look your history to see how it evolved.
But first I'm. Going to copy the hyperland and eww and install the fonts to my simple flake and see if I can just that working then I can little by little install all the other things on by one that you have in yours to learn step by step..

I would like to contact you in discord. But what channel are you in? Hyprland or some other nixos channel?

Thanks again

**Comment by fufexan** [comment]
> I would like to contact you in discord. But what channel are you in? Hyprland or some other nixos channel?

Both the Hyprland server and the NixOS unofficial server. My tag is visible on my github profile, but I'll put it here as well: `fufexan#1006`.
