### ISSUE TITLE
Build VM Configuration for those who want to try out the Nix-OS config ?

### ISSUE THREAD

**Issue by lalishansh** [fufexan/dotfiles#41]
I Ran `nixos-rebuild build-vm --flake '.#io'` to build a VM out of this NixOS config.

after some time (its 4.5 GB download for those who have limited bandwidth), it gave me blank screen.

followed [Hyprland on NixOS vm/QEMU](https://github.com/hyprwm/Hyprland/issues/1056)

to add 
```
    -device virtio-vga-gl \
    -display sdl,gl=on,show-cursor=on \
```
in `run-io-vm.sh` (by copying it to local file and making it executable)

The Inputs are not working.
NOTE: i have Nvidia GPU, but i also have Radeon iGPU

**Comment by fufexan** [comment]
> The Inputs are not working.

What do you mean by this?

**Comment by lalishansh** [comment]
Keyboard input, trying to enter password etc.
Note: i modified config for `initialPassword`

**Comment by fufexan** [comment]
I don't normally use VMs, so I don't know what the issue could be. Do configs with other compositors work?

**Comment by lalishansh** [comment]
I've used the Aylur's dotfiles for the same and it works. (after commenting gnome-secrets but that's not important).

Edit: build-vm is awesome for testing configs (one of the awesome features i like about NixOS)
