### ISSUE TITLE
[TLauncher] Maybe Malware !!

### ISSUE THREAD

**Issue by semi710** [fufexan/dotfiles#5]
was checking out your dots and found [TLauncher](https://tlauncher.org/) [here](https://github.com/fufexan/dotfiles/blob/main/pkgs/tlauncher.nix#L14) 

At Multiple places, I have seen it to be flagged as malware from Russia.

[Original](https://tlaun.ch/?lang=en) Tlauncher is now with the name legacy. their [Discord](https://discord.com/invite/cVJuz5R)

**Comment by fufexan** [comment]
Oh it seems so. I haven't really used/installed it in a few months, so I wasn't aware. Thanks for letting me know!

So you're saying I should grab the tlaun.ch version or is that also malware?

**Comment by semi710** [comment]
> Oh it seems so. I haven't really used/installed it in a few months, so I wasn't aware. Thanks for letting me know!
> 
> So you're saying I should grab the tlaun.ch version or is that also malware?

tlaun.ch one is not malware have been using it for a long time.
Their community support is good too.
