### ISSUE TITLE
Path to home manager module for eww-hyprland is not correct

### ISSUE THREAD

**Issue by sandangel** [fufexan/dotfiles#8]
https://github.com/fufexan/dotfiles/blob/main/home/profiles/default.nix#L55

I think it should be `../programs/eww`

**Comment by fufexan** [comment]
Oops, you're right!

**Comment by fufexan** [comment]
Fixed in https://github.com/fufexan/dotfiles/commit/aeed85c84fe9ba2f4996a3b388b542f698b81677.
