### ISSUE TITLE
How to remove .nix-profile and .nix-defexpr/

### ISSUE THREAD

**Issue by hmanhng** [fufexan/dotfiles#9]
I use Flake and the .nix-profile file and .nix-defexpr/ folder seem to be useless. Is there any way to prevent them from appearing in my HOME directory?

**Comment by fufexan** [comment]
`.nix-profile` is not useless. It's where Home Manager links your user's PATH, among other things. Removing it will leave you with only system-wide commands available to use.

I'm not sure about `.nix-defexpr`, it can probably be removed but it hasn't bothered me so I don't know if there's a way to do it.

**Comment by hmanhng** [comment]
My .nix-profile symbolic to .local/state/nix/profiles/profile instead of .local/state/nix/profiles/home-manager, so it doesn't exist. I don't know why it's like that.

**Comment by fufexan** [comment]
`/home/mihai/.nix-profile: symbolic link to /nix/var/nix/profiles/per-user/mihai/profile`

Also, `.nix-defexpr` only gets created when using nix 2.3 commands. Tested by removing it and running `nix-shell -p hello`.

**Comment by hmanhng** [comment]
I have figured out how to add them to xdg_state by setting use-xdg-base-directories = true in nix.conf.

**Comment by fufexan** [comment]
That's helpful! I'll add it as well.
